package correctSolutions;

public class Cashcards 
{

	String Bankname;
	float balance;
	float shoppingamount;

	
	
	 public Cashcards(String bankname, float shoppingamount) {
		super();
		Bankname = bankname;
		
		this.shoppingamount = shoppingamount;
	}
	
	void swipe()
	 {
		 
	 }
	

	}
	
	
	
	
	
class creditcard extends Cashcards
{

	public creditcard(String bankname, float shoppingamount) {
		super(bankname, shoppingamount);
		
	}
	
	void swipe()
	{
		System.out.println(" credit card is used to pay: rs "+ shoppingamount);
		
		
	}
	void displayinfo(){
		
		System.out.println(" bankname :"+Bankname);
		System.out.println("shopping amount is"+shoppingamount);
		
	}
	
	
	
	
	
	
	
}

class Debitcard extends Cashcards
{

	public Debitcard(String bankname, float shoppingamount) {
		super(bankname, shoppingamount);
		balance=8000f;
	}
	
	void swipe()
	{
		
		System.out.println("balance generated by credit card which is payed through debitcard is "+ this.paybalance());
		
		
	}
	
	
	float paybalance(){
		if(balance>shoppingamount)
		{balance=balance-shoppingamount;
		return balance;
		}
		else
			{
			System.out.println("less balance in debitcard ..cant pay amount");
			return 0f;
			}
		
		
	}
void displayinfo(){
		
		System.out.println(" bankname :"+Bankname);
		
	}
	
	
}

